### ISSUE TITLE
error: 'class WiFiClass' has no member named 'setSortMethod'

### ISSUE THREAD

**Issue by stosoorok** [raomin/ESPAltherma#438]
Platformio fails, when I try to build latest version. 

I got two errors:

`src\main.cpp: In function 'void setup_wifi()':
src\main.cpp:218:8: error: 'class WiFiClass' has no member named 'setSortMethod'
   WiFi.setSortMethod(WIFI_CONNECT_AP_BY_SIGNAL);
        ^
src\main.cpp:219:8: error: 'class WiFiClass' has no member named 'setScanMethod'
   WiFi.setScanMethod(WIFI_ALL_CHANNEL_SCAN);
        ^
src\main.cpp: In function 'void setup()':
src\main.cpp:357:53: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
   Serial.printf("Wifi client timeout: %d\n", timeout);`

Any ideas?

![image](https://github.com/raomin/ESPAltherma/assets/30243517/c8622b5b-8c85-4c71-a846-a8089ebdf915)

![image](https://github.com/raomin/ESPAltherma/assets/30243517/2728e6e2-a5cd-47c0-896e-6a289ee24656)

**Comment by raomin** [comment]
Probably some framework breaking change. I'll have a look.

**Comment by stosoorok** [comment]
Thanks. BTW, where did you enable ESP wifi signal strength? I can't find it.

**Comment by Rapanter01** [comment]
Hello, i have the same issue.
Did you found a solution?
Thanks

**Comment by raomin** [comment]
That's weird, I get a successful build with the latest framework (6.7.0).

Can you try to force it: 
`platform = espressif32 @ 6.7.0`

or try to revert to an older one:
`platform = espressif32 @ 6.4.0`

Note: you can also remove the two lines, it should work just fine.

RE: Wifi signal, the wifi signal threshold was removed for, normally, getting always the best ssid.
At one point, we should move to `WiFiMulti.h`.

**Comment by stosoorok** [comment]
Thnx @raomin I commented out these lines yesterday and I was able to compile it and upload. Scratch that wifi rssi. I was using your first version of ESPAltherma which has worked great. I see that many things have changed meanwhile.

I uploaded it via USB. I was not able to get it to upload via espota. What I am missing here?

**Comment by raomin** [comment]
The setSortMethod call is now guarded so ESP8266 builds again, and the ESP32 platform version is pinned in platformio.ini. Closing.
